[project]
name = "codurance-katas"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "spacy>=3.8.7",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
